### ISSUE TITLE
#1 New CustomSortingScript for OASIS data

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/CustomScripts#1]
This is the script to sort OASIS data in this structure:
 sub-OAS30048/ses-d1717

- dataset_description.json (from ./BIDS)
- anat 
        sub-OAS30048_ses-d1717_run-01_T1w.json     (run01 and 02) 
        sub-OAS30048_ses-d1717_run-01_T1w.nii.gz 
        (inside anat we only want T1, T2, FLAIR, not TOF_angio files)
        all ending T1w,T2w, FLAIR + json/nii.gz/nii, the 'run' doesn't have to be there and sometimes there is 'echo_x'
- perf 
        sub-OAS30048_ses-d1717_run-01_asl.json -> Correct json files (with Jan’s functions) 
        sub-OAS30048_ses-d1717_run-01_asl.nii.gz 
        [these ASL files are now inside func folders] 
- fmap
    (all files inside fmap1, fmap2, etc should go to a single directory called fmap) 
- Other 
        Swi 
        TOF_angio
- sub_AV_ses (these just ignore actually)
- sub_PIB_ses (these just ignore actually)
- WMH_SEG files should be extracted from the folder that is already “processed”
        sub-OAS30048_ses-d1717_WMHSEG.nii.gz

**Comment by MichaelStritt** [comment]
Sorry, stupid question, does c5e9fca633607be7efa9660f19be634aab17a0c5 create BIDS **rawdata** or **derivatives** (so legacy format) now?

**Comment by MichaelStritt** [comment]
Okay, so right now we get an output structure like this:

```
/OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../anat/
```

And in the end we probably want to have:

```
/OASIS/rawdata/sub-OAS.../ses-.../anat/
```

Right?

**Comment by MichaelStritt** [comment]
And instead of:

```
/OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../anat/...T1.nii
/OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../anat/...FLAIR.nii
```

We want:

```
/OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../anat/...T1.nii
/OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../flair/...FLAIR.nii
```

Right?

**Comment by BeatrizPadrela** [comment]
No, no, I think that FLAIR, T1 and T2 should be inside anat. See the structure of the issue, Jan corrected that one :)

**Comment by BeatrizPadrela** [comment]
> Okay, so right now we get an output structure like this:
> 
> ```
> /OASIS/derivatives/ExploreASL/sub-OAS.../ses-.../anat/
> ```
> 
> And in the end we probably want to have:
> 
> ```
> /OASIS/rawdata/sub-OAS.../ses-.../anat/
> ```
> 
> Right?

Already done :D

**Comment by MichaelStritt** [comment]
Perfect, so we could initialize the iterator for an empty list in the beginning of the script:

```matlab
iElement = 1;
```

And then we read each json file like this:

```matlab
json = jsonread(filename.json);
```

And we extract the necessary information:

```matlab
if isfield(json,'ManufacturerModelName')
    scannerList(iElement,1) = json.ManufacturerModelName;
    scannerList(iElement,2) = current_subject;
    iElement = iElement+1;
end
```

**Comment by MichaelStritt** [comment]
Okay, so if there are different scanners for different sessions, we could do something like:

```matlab
if isfield(json,'ManufacturerModelName')
    scannerList{iS1,1} = current_subject;
    scannerList{iS1,1} = current_session;
    scannerList{iS1,3} = json.ManufacturerModelName;
    iElement = iElement+1;
end
```

**Comment by BeatrizPadrela** [comment]
iElement can be the iS1 as we discussed

**Comment by BeatrizPadrela** [comment]
> ```matlab
> if isfield(json,'ManufacturerModelName')
>     scannerList{iS1,1} = current_subject;
>     scannerList{iS1,1} = current_session;
>     scannerList{iS1,3} = json.ManufacturerModelName;
>     iElement = iElement+1;
> end
> ```

iElement can be iS1 as we discussed, so:

if isfield(json,'ManufacturerModelName')
    scannerList{iS1,1} = current_subject;
    scannerList{iS1,1} = current_session;
    scannerList{iS1,3} = json.ManufacturerModelName;
    iS1 = iS1+1;
end

**Comment by BeatrizPadrela** [comment]
if isfield(json,'ManufacturerModelName')
    scannerList{iS1,1} = current_subject;
    scannerList{iS1,1} = current_session;
    scannerList{iS1,3} = json.ManufacturerModelName;
    iS1 = iS1+1;
end

**Comment by BeatrizPadrela** [comment]
Ok perfect!
And we can use iS1 instead of iElement, as we discussed, so ending with iS1=iS1+1;

**Comment by BeatrizPadrela** [comment]
We actually want this inside the iType for loop, because the ScanList correspond to the folders anat1,anat2,fmap1,fmap2
And I'm going to change the first iType for t1w, because they should all have t1w
so, in line 49:

```
for iType=1:length(ScanType)
    if iType==1 % Extract information from first scan every time
        if isfield(json,'ManufacturerModelName')
            scannerList{iS1,1} = current_subject;
            scannerList{iS1,1} = current_session;
            scannerList{iS1,3} = json.ManufacturerModelName;
            iS1 = iS1+1;
        end
    end
    ...
end
```

**Comment by MichaelStritt** [comment]
Okay, I think this is the way to go:

```matlab
    if strcmp(ScanType{iType},'T1w') % Extract information from first scan every time
        if isfield(json,'ManufacturerModelName')
            scannerList{iElement,1} = current_subject;
            scannerList{iElement,1} = current_session;
            scannerList{iElement,3} = json.ManufacturerModelName;
            iElement = iElement+1;
        end
    end
```

We shouldn't use `iS1 = iS1+1;` since this would change the subject numbers. And we probably shouldn't `iS1`, since we have to iterate over both subjects & sessions (`iS1` are only the subjects).

The easiest place would probably be directly after line **87**. Here we have...

```
xASL_Copy(BIDSlist{iBids}, DestFile, true);
```

With `BIDSlist{iBids}` being the path of the JSON file we save, right?

Let's try this starting at line **87**:

```matlab
    xASL_Copy(BIDSlist{iBids}, DestFile, true);
    if strcmp(ScanType{iType},'T1w') % Extract information from first scan every time
        json = spm_jsonread(BIDSlist{iBids});
        if isfield(json,'ManufacturerModelName')
            scannerList{iElement,1} = current_subject;
            scannerList{iElement,1} = current_session;
            scannerList{iElement,3} = json.ManufacturerModelName;
            iElement = iElement+1;
        end
    end
```

**Comment by MichaelStritt** [comment]
And then maybe something like this:

```matlab
root = 'OUTPUT_DIR';

for iScanner = 1:length(scanners)
    
    % Create the output directory for the current scanner type
    mkdir(fullfile(root,scanners(iScanner))); 
    
    % Copy all subjects that have this type to the directory
    for iElement = 1:size(scannerList,2)
        if strcmp(scannerList{iElement,3},scanners(iScanner))
            source = fullfile(root,scanners(iScanner),...);
            destination = fullfile(root,scanners(iScanner),...);
            xASL_Copy(source,destination,...); % Use the recursive option
            
        end
        
    end
    
end
```

But if you think there's a better way to do this go ahead ;)

**Comment by BeatrizPadrela** [comment]
So, the list of scanners gave something like this: (for the first 5 subjects)

```
'sub-OAS30001'    'ses-d2430'    'Biograph_mMR'
    'sub-OAS30001'    'ses-d3132'    'TrioTim'     
    'sub-OAS30002'    'ses-d2340'    'Biograph_mMR'
    'sub-OAS30002'    'ses-d2340'    'Biograph_mMR'
    'sub-OAS30002'    'ses-d2345'    'TrioTim'     
    'sub-OAS30003'    'ses-d1631'    'TrioTim'     
    'sub-OAS30003'    'ses-d1631'    'TrioTim'     
    'sub-OAS30003'    'ses-d2669'    'TrioTim'     
    'sub-OAS30003'    'ses-d2682'    'Biograph_mMR'
    'sub-OAS30003'    'ses-d3731'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d2229'    'TrioTim'     
    'sub-OAS30004'    'ses-d2229'    'TrioTim'     
    'sub-OAS30004'    'ses-d2232'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d2232'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d3457'    'Biograph_mMR'
    'sub-OAS30005'    'ses-d1274'    'TrioTim'     
    'sub-OAS30005'    'ses-d1274'    'TrioTim'     
    'sub-OAS30005'    'ses-d2377'    'TrioTim'     
    'sub-OAS30005'    'ses-d2384'    'Biograph_mMR'
    'sub-OAS30005'    'ses-d3453'    'Biograph_mMR'
```


> Okay perfect, so now we need to get the list of scanners, right?
> So for example like this:
> 
> ```
> testList =
>     {'patient1'}    {'session'}    {'scannerA'}
>     {'patient2'}    {'session'}    {'scannerA'}
>     {'patient3'}    {'session'}    {'scannerB'}
> ```
> 
> To get the unique scanners:
> 
> ```
> scanners = unique([testList(:,3)]);
> ```


So the scannerList is something like this: (for the first 5 subjects)

'sub-OAS30001'    'ses-d2430'    'Biograph_mMR'
    'sub-OAS30001'    'ses-d3132'    'TrioTim'     
    'sub-OAS30002'    'ses-d2340'    'Biograph_mMR'
    'sub-OAS30002'    'ses-d2340'    'Biograph_mMR'
    'sub-OAS30002'    'ses-d2345'    'TrioTim'     
    'sub-OAS30003'    'ses-d1631'    'TrioTim'     
    'sub-OAS30003'    'ses-d1631'    'TrioTim'     
    'sub-OAS30003'    'ses-d2669'    'TrioTim'     
    'sub-OAS30003'    'ses-d2682'    'Biograph_mMR'
    'sub-OAS30003'    'ses-d3731'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d2229'    'TrioTim'     
    'sub-OAS30004'    'ses-d2229'    'TrioTim'     
    'sub-OAS30004'    'ses-d2232'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d2232'    'Biograph_mMR'
    'sub-OAS30004'    'ses-d3457'    'Biograph_mMR'
    'sub-OAS30005'    'ses-d1274'    'TrioTim'     
    'sub-OAS30005'    'ses-d1274'    'TrioTim'     
    'sub-OAS30005'    'ses-d2377'    'TrioTim'     
    'sub-OAS30005'    'ses-d2384'    'Biograph_mMR'
    'sub-OAS30005'    'ses-d3453'    'Biograph_mMR'
```

**Comment by BeatrizPadrela** [comment]
> Okay perfect, so now we need to get the list of scanners, right?
> So for example like this:
> 
> ```
> testList =
>     {'patient1'}    {'session'}    {'scannerA'}
>     {'patient2'}    {'session'}    {'scannerA'}
>     {'patient3'}    {'session'}    {'scannerB'}
> ```
> 
> To get the unique scanners:
> 
> ```
> scanners = unique([testList(:,3)]);
> ```

So the scannerList is something like this: (for the first 5 subjects)

```
'sub-OAS30001' 'ses-d2430' 'Biograph_mMR'
'sub-OAS30001' 'ses-d3132' 'TrioTim'
'sub-OAS30002' 'ses-d2340' 'Biograph_mMR'
'sub-OAS30002' 'ses-d2340' 'Biograph_mMR'
'sub-OAS30002' 'ses-d2345' 'TrioTim'
'sub-OAS30003' 'ses-d1631' 'TrioTim'
'sub-OAS30003' 'ses-d1631' 'TrioTim'
'sub-OAS30003' 'ses-d2669' 'TrioTim'
'sub-OAS30003' 'ses-d2682' 'Biograph_mMR'
'sub-OAS30003' 'ses-d3731' 'Biograph_mMR'
'sub-OAS30004' 'ses-d2229' 'TrioTim'
'sub-OAS30004' 'ses-d2229' 'TrioTim'
'sub-OAS30004' 'ses-d2232' 'Biograph_mMR'
'sub-OAS30004' 'ses-d2232' 'Biograph_mMR'
'sub-OAS30004' 'ses-d3457' 'Biograph_mMR'
'sub-OAS30005' 'ses-d1274' 'TrioTim'
'sub-OAS30005' 'ses-d1274' 'TrioTim'
'sub-OAS30005' 'ses-d2377' 'TrioTim'
'sub-OAS30005' 'ses-d2384' 'Biograph_mMR'
'sub-OAS30005' 'ses-d3453' 'Biograph_mMR'
```

**Comment by MichaelStritt** [comment]
Almost there ;)

Okay, so regarding this:

```matlab
% Copy all subjects that have this type to the directory
for iElement = 1:size(scannerList,2)
    if strcmp(scannerList{iElement,3},scanners{iScanner})
        source = fullfile(root,scanners{iScanner});
        FinalDest = fullfile(root,scanners{iScanner});
        xASL_Copy(source,FinalDest); % Use the recursive option
   end
end
```

We probably only have to fix the source & destination now, right? Maybe something like this works, but you probably need to debug it a bit:

```matlab
% Copy all subjects that have this type to the directory
for iElement = 1:size(scannerList,2)
    if strcmp(scannerList{iElement,3},scanners{iScanner})
        source = fullfile(root,scannerList{iElement,1},scannerList{iElement,2});
        FinalDest = fullfile(root,scanners{iScanner},scannerList{iElement,1},scannerList{iElement,2});
        xASL_Move(source,FinalDest,true);
   end
end
```
Does xASL_Move work recursively there? It is, right? The benefit of moving is that we can see if all subjects/sessions were moved and it didn't skip some.

**Comment by MichaelStritt** [comment]
By the way, these `.m~` files are Matlab autosave files ([source](https://stackoverflow.com/questions/5351629/matlab-saves-copies-of-files-with-extension-m-what-do-they-do-can-i-turn-the)). We probably do not want them in the repository. I can show you how you can get rid of them using the `.gitignore` option.

**Comment by BeatrizPadrela** [comment]
The names of the final folders are now in format they should be: Siemens_Biograph_mMR_51010_syngo_MR_B18P, with the information from:
```
"Manufacturer": "Siemens",
    "ManufacturersModelName": "TrioTim",
    "DeviceSerialNumber": "35248",
    "PatientPosition": "HFS",
    "SoftwareVersions": "syngo_MR_B17"
```
Now there's just one step left:
-> Copy the WMH_SEG from OASIS/derivatives/ExploreASL_PreviousRun

**Comment by BeatrizPadrela** [comment]
Top! everything works and subjects with no ASL can go to a folder  that is not one of the scanners folders, as @jan-petr asked :)
I tested everything with a 'test_sourcedata' with only 5 subjects form OASIS.

When you want to run them all just let me know! Maybe you want to check the code first :)

**Comment by BeatrizPadrela** [comment]
The WMH files part is commented because we don't need the WMH files inside the rawdata folder. We can add these lines when working with 'derivatives' as output directory.
The jsons for scans with different runs were not being added to the folders, but that was already corrected as well
