### ISSUE TITLE
ADNI to ASL-BIDS

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/CustomScripts#7]
Methods to convert the ADNI-2 and ADNI-3 [databases](http://adni.loni.usc.edu/) to ASL-BIDS.

@HenkMutsaerts & @jan-petr: I updated most of my methods and added them to the custom scripts repository.

**Comment by MichaelStritt** [comment]
### Download and data validation

After download I got a lot of different zip files and the unpacking took a while. To validate that everything worked, I wrote the script `xASL_adni_ValidateDatasets`. You can insert the **label CSV file** as well as the case directory and it tells you if all the cases of the label file exist. The output should look like this:

```terminal
Compare local database with subjects from label file...
Number of cases is correct...
Lists are identical...
```

**Comment by MichaelStritt** [comment]
### Convert to source data

We spent a lot of time trying to figure out all relevant parameters. We came to the following settings:

- PLD = 1900ms (ADNI-2), PLD = 2000ms (ADNI-3)
- Labeling duration = 700ms
- 2D: SliceReadoutTime = 27.5ms (B15 scanners), SliceReadoutTime = 42ms (other scanners)

Some scans have a dummy M0 / real M0 within the 2D sequence. You can use `M0PositionInASL4D` or the new option that we are adding for OASIS. Most of the details are within the actual conversion script `xASL_adni_Convert2Source`. Here the output should look like this:

```console
Searching for ADNI cases with ASL scans...
Determining sessions from date strings...
Copy 009_S_0751... 00%
Copy 009_S_0842... 00%
Copy 009_S_1030... 00%
Copy 009_S_2208... 01%
Copy 009_S_2381... 01%
Copy 009_S_4324... 01%
...
```

**Comment by MichaelStritt** [comment]
### Actual conversion to ASL-BIDS

Right now there still seems to be a small bug related to the `ASL Context` within the second import module. Most of the code seems to work though. We use the up-to-date **ExploreASL** version to convert the data to BIDS rawdata and then to the **ExploreASL** legacy format with `xASL_adni_Convert2BIDS`.

```console
Import 009_S_0751... 20%
ExploreASL will run the import workflow and will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
Dataset Root        M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\adni-2\009_S_0751
Import Modules      DCM2NII NII2BIDS BIDS2LEGACY
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 

Matching files:
    'sub-001\session_1_2012-09-06_14_03_30.0\ASL\S166401'
    'sub-001\session_2_2013-09-13_08_00_06.0\ASL\S201455'
    'sub-001\session_3_2014-09-04_14_52_59.0\ASL\S232241'
    'sub-001\session_2_2013-09-13_08_00_06.0\FLAIR\S201461'
    'sub-001\session_3_2014-09-04_14_52_59.0\FLAIR\S232240'
    'sub-001\session_2_2013-09-13_08_00_06.0\T1w\S201462'
    'sub-001\session_3_2014-09-04_14_52_59.0\T1w\S232247'

#=7
Running import (i.e. dcm2niiX)
==============================================================================================
Importing subject=sub-001_1:   
>>> Subject=sub-001, visit=1, session=1, scan=ASL4D
...
==============================================================================================
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
...
==============================================================================================
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
...
==============================================================================================
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
...
==============================================================================================
...
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion, DatasetType, License
NIfTI to BIDS module failed:
Reference to non-existent field 'ASLContext'.
```

**Comment by MichaelStritt** [comment]
### Preliminary results

You should get a folder structure like this:

![image](https://user-images.githubusercontent.com/46593074/124606455-319b6080-de6d-11eb-8f78-0f12d0a6ea7f.png)

When the second module is fixed, you should also get a `derivatives` folder and the `temp` should disappear.

The **JSONs** are populated automatically and should be okay:

![image](https://user-images.githubusercontent.com/46593074/124606568-4ed02f00-de6d-11eb-9869-1953d8a87bb3.png)

![image](https://user-images.githubusercontent.com/46593074/124606640-5f80a500-de6d-11eb-8f3e-1840eeb03216.png)

**Comment by MichaelStritt** [comment]
@jan-petr: It's a bit weird. Do we really need the `ASL Context` in the studyPar.json? Manually fixing it here b335539ab13e1e63e52d24631a275863b7045537 does seem a bit troublesome. Other than that everything seems to work quite nicely.

**Comment by MichaelStritt** [comment]
Saw the fix within the FlavorDatabase. I Implemented it in a similar way within ee674f36f18926f871c8f0d5223382d8e200f3da.

**Comment by MichaelStritt** [comment]
### Test (4 ADNI datasets, 2D EPI)

![image](https://user-images.githubusercontent.com/46593074/124739674-62859f00-df1a-11eb-9c6c-5dfd96ada1c6.png)

![image](https://user-images.githubusercontent.com/46593074/124739751-73361500-df1a-11eb-80e7-214ffacc1185.png)

![image](https://user-images.githubusercontent.com/46593074/124739795-7df0aa00-df1a-11eb-9111-d6211fa32950.png)

![image](https://user-images.githubusercontent.com/46593074/124739937-96f95b00-df1a-11eb-987e-03cb6b13a6a0.png)

**Comment by MichaelStritt** [comment]
I'm not sure, but I think the multiple sessions don't work correctly yet. I'll try to fix that.

**Comment by sandeepganji** [comment]
Does the ADNI dicom have xx files in them?

**Comment by MichaelStritt** [comment]
> Does the ADNI dicom have xx files in them?

I mostly worked with ADNI-2 & ADNI-3 Siemens Scans so far, but a colleague mentioned Philips too. I'll check it out.

**Comment by H-Snoussi** [comment]
Yes, there is also Philips data in ADNI. I downloaded the dicom files, then converted them using dcm2niix

**Comment by MichaelStritt** [comment]
Hey @H-Snoussi, I'm currently working on https://github.com/ExploreASL/ExploreASL/issues/717 and we can hopefully merge this tomorrow. The most recent commit 2819b93 seems to fix most of the problems. I still have to fix the code so that we can run multiple sessions for a single subject, but probably the `dataPar.json` or the BIDS conversion aren't correct, yet.
I'm running a few tests tonight and will try to improve it tomorrow, but my calendar seems pretty full. The processing does seem to start correctly though:

![image](https://user-images.githubusercontent.com/46593074/125823024-5471b92f-01e3-4308-8933-0fd4b698fe46.png)

**Comment by MichaelStritt** [comment]
@H-Snoussi: Should be possible to import multiple sessions now. The code should mostly be fixed. @jan-petr helped me a lot with the correction of the sourceStructure file. 

![image](https://user-images.githubusercontent.com/46593074/126194348-209fa9ce-b398-4a3b-bb97-ed9740056437.png)

There's still a bit of room for improvement. The individual visits should rather be sub-001-1 instead of sub-0011, but it should still be possible to run the processing.

![image](https://user-images.githubusercontent.com/46593074/126194487-ca1f20d8-c74e-4a6f-8990-1b14242a2236.png)

I'll check out the Philips and ADNI-3 data next and will start to build up the database at the AMC.

**Comment by MichaelStritt** [comment]
@H-Snoussi: I had a look at the Philips and GE datasets. Did a minor fix in b227375. For testing 006_S_6681 and 027_S_5079 seem pretty good. I guess a few processing parameters are still missing. I have to check the study protocols for that first. Creating a basic sourceStructure with the current code seems to work though.

**Comment by MichaelStritt** [comment]
### To-do list

- Get correct acquisition parameters for ADNI-2/ADNI-3 Siemens/Philips/GE
- Test processing of one dataset each

**Comment by MichaelStritt** [comment]
@H-Snoussi & @jan-petr: Ahhh okay, I think I get the problem with the Philips scans now. At least the one that I checkout out seems to be a deltam image already. I couldn't find the corresponding M0. This means we can't use an M0 and we kind of can't use control scans as dummy M0s. In addition our workflows can't automatically extract the SliceTimings right now.

**Comment by MichaelStritt** [comment]
Okay, so the fix 8c8bb8d is really not the correct way to do this, but at least it's possible to run the full import workflow with it:

![image](https://user-images.githubusercontent.com/46593074/126633643-96cdf008-3e9c-4dc8-8bb7-602356f83380.png)

![image](https://user-images.githubusercontent.com/46593074/126633734-8f6a63bc-236d-418d-bdc3-d30f07096b2c.png)

![image](https://user-images.githubusercontent.com/46593074/126633760-c687076b-da60-409a-b503-37cc609588af.png)

![image](https://user-images.githubusercontent.com/46593074/126633785-18163128-25fb-4f69-bd65-e748b08f5bc8.png)

**Comment by MichaelStritt** [comment]
Fix https://github.com/ExploreASL/ExploreASL/issues/732 and add participants tsv files with subject, visit, date etc.

**Comment by MichaelStritt** [comment]
With 5f78963 it should be possible to automatically create participants.tsv files now, which will be helpful for the identity of sessions with the label file.

**Comment by H-Snoussi** [comment]
@MichaelStritt 
**For Siemens data**: I think that we should use xasl.MRAcquisitionType instead of xasl.PulseSequenceType. We have "MRAcquisitionType" field in the Json files of Siemens data; its value is "2D" or "3D". In addition, for x.Sequence parameter, I think we could take this parameter directly from the Json file of Siemens data; there is a field named "ScanningSequence". Its value is "EP" for all Siemens data.

**Comment by H-Snoussi** [comment]
Sorry, it was a typo.

**Comment by MichaelStritt** [comment]
@H-Snoussi no worries. I'm trying to fix remaining bugs with jan right now. some of the defaults/fallbacks were a bit stupid and I have to move some parameters from dataPar.json to studyPar.json. The code mainly works with develop, so if something crashes try to use develop instead of main.

**Comment by H-Snoussi** [comment]
@MichaelStritt, I think that there is another missing parameter "BackgroundSuppressionNumberPulses".

**Comment by MichaelStritt** [comment]
> @MichaelStritt, I think that there is another missing parameter "BackgroundSuppressionNumberPulses".

Yes, that's one of the BIDS parameters which is quite hard to find out if you don't know the exact protocol.
I'm running some tests with different ADNI-2 and ADNI-3 flavors today, since another student also asked for the conversion. Will probably push some updates for CustomScripts later today.

**Comment by MichaelStritt** [comment]
So, I added a list of datasets that should work nicely (b5917a3 & ddfa53e ). Some are still a bit problematic because of a few missing **BIDS parameters** or because the import crashes as a result of unexpected **dcm2niix** output, _I think_. I'm processing more datasets now and will try to fix the problems. I've started with ADNI-3 and after that I'll go on to ADNI-2 and ADNI-GO.
